/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Evaluator {
  /**
   * Rebuild a `Context` under `Params::unsecure()` and load the
   * serialized evaluation key produced by the browser client.
   */
  static load(ekBytes: Buffer): Evaluator
  /**
   * Homomorphic `a + b` over serialized `u32` ciphertexts. Returns the
   * serialized result.
   */
  addU32(a: Buffer, b: Buffer): Buffer
}
